import { expect, test } from "@playwright/test";

test("seconds source, placement and rate work independently and persist", async ({ page }, info) => {
  await page.clock.install();
  await page.goto("/");
  await page.getByRole("button", { name: "Select Apex", exact: true }).click();
  await page.getByRole("button", { name: "Design studio", exact: true }).first().click();
  await page.locator("summary").filter({ hasText: "Signature & light" }).click();
  await page.getByLabel("Seconds indication", { exact: true }).selectOption("running");
  await page.getByLabel("Seconds placement", { exact: true }).selectOption("peripheral");
  await page.getByLabel("Seconds motion", { exact: true }).selectOption("stepped");
  await page.getByLabel("Seconds advances per second", { exact: true }).selectOption("16");
  const hand = page.locator(".watch-stage [data-seconds-hand]");
  await expect(hand).toHaveCount(1);
  await expect(hand).toHaveAttribute("data-seconds-placement", "peripheral");
  await expect(hand).toHaveAttribute("data-seconds-advances", "16");
  const before = await hand.getAttribute("transform");
  await page.clock.fastForward(1500);
  await expect(hand).not.toHaveAttribute("transform", before!);
  await page.getByLabel("Seconds indication", { exact: true }).selectOption("chronograph");
  await expect(hand).toHaveAttribute("transform", "rotate(0 320 350)");
  await page.clock.fastForward(3000);
  await expect(hand).toHaveAttribute("transform", "rotate(0 320 350)");
  await page.getByRole("button", { name: "Start chronograph", exact: true }).click();
  await page.clock.fastForward(5500);
  await page.getByRole("button", { name: "Pause chronograph", exact: true }).click();
  const stopped = await hand.getAttribute("transform");
  expect(stopped).not.toBe("rotate(0 320 350)");
  await page.clock.fastForward(3100);
  await expect(hand).toHaveAttribute("transform", stopped!);
  await page.getByLabel("Seconds indication", { exact: true }).selectOption("none");
  await expect(hand).toHaveCount(0);
  await page.getByLabel("Seconds indication", { exact: true }).selectOption("running");
  await page.getByLabel("Seconds placement", { exact: true }).selectOption("small");
  await expect(hand).toHaveAttribute("data-seconds-placement", "small");
  await expect(page.locator('.watch-stage [data-chronograph-hand="hours"]')).toHaveCount(0);
  await page.locator("summary").filter({ hasText: "Reference specifications" }).click();
  await page.getByLabel("Setting behavior", { exact: true }).selectOption("zero-reset");
  await page.getByLabel("Chronograph behavior", { exact: true }).selectOption("flyback");
  await expect(page.locator(".reference-specifications")).toContainText("design notes");
  await page.getByRole("button", { name: "Add to collection", exact: true }).click();
  await page.getByLabel("Watch name", { exact: true }).fill("Stepped seconds edition");
  await page.getByRole("button", { name: "Save watch", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.reload();
  await expect(hand).toHaveAttribute("data-seconds-placement", "small");
  await expect(hand).toHaveAttribute("data-seconds-advances", "16");
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("watchme.fixture.studio.v1")!).watches[0].design);
  expect(saved.secondsSetting).toBe("zero-reset");
  expect(saved.chronographBehavior).toBe("flyback");
  await page.screenshot({ path: info.outputPath("seconds-independent.png") });
});
