"use client";
import { useState } from "react";
import { Flag, Pause, Play, RotateCcw, Volume2, VolumeX } from "lucide-react";
import { formatDuration } from "@/lib/timers";
import type { useTimers } from "@/hooks/use-timers";
export function Instruments({ timers }: { timers: ReturnType<typeof useTimers> }) {
  const [tab, setTab] = useState<"chronograph" | "countdown">("chronograph");
  const [minutes, setMinutes] = useState(String(timers.state.countdown.duration / 60000));
  const running = timers.state.chronograph.startedAt !== null;
  return <div className="instruments"><div className="instrument-tabs segmented"><button className={tab === "chronograph" ? "selected" : ""} onClick={() => setTab("chronograph")}>Chronograph</button><button className={tab === "countdown" ? "selected" : ""} onClick={() => setTab("countdown")}>Countdown</button></div>
    {tab === "chronograph" ? <><div className="instrument-readout"><p className="eyebrow">{running ? "MEASURING THE MOMENT" : "PRECISION, ON DEMAND"}</p><output>{formatDuration(timers.elapsed, true)}</output><span>HOURS / MINUTES / SECONDS</span></div><div className="timer-controls"><button className="icon-button outlined" onClick={timers.chronoReset} aria-label="Reset chronograph"><RotateCcw size={19}/></button><button className="button-primary" onClick={timers.chronoToggle}>{running ? <Pause size={17}/> : <Play size={17}/>} {running ? "Pause" : timers.elapsed ? "Resume" : "Start"}</button><button className="icon-button outlined" disabled={!running} onClick={timers.lap} aria-label="Record lap"><Flag size={19}/></button></div>{timers.state.chronograph.laps.length > 0 && <div className="lap-list"><div className="lap-header"><span>LAP</span><span>SPLIT</span><span>TOTAL</span></div>{timers.state.chronograph.laps.map((time, i, laps) => <div key={`${i}-${time}`}><span>{String(i + 1).padStart(2, "0")}</span><span>{formatDuration(time - (laps[i - 1] || 0), true)}</span><span>{formatDuration(time, true)}</span></div>).reverse()}</div>}</> : <><div className={`instrument-readout ${timers.state.countdown.completed ? "timer-complete" : ""}`}><p className="eyebrow">{timers.state.countdown.completed ? "YOUR MOMENT HAS ARRIVED" : "MAKE TIME FOR WHAT MATTERS"}</p><output aria-live={timers.state.countdown.completed ? "polite" : "off"}>{timers.state.countdown.completed ? "Time’s up." : formatDuration(timers.remaining)}</output><span>{timers.state.countdown.completed ? "COUNTDOWN COMPLETE" : "MINUTES / SECONDS"}</span></div><div className="duration-field"><label htmlFor="countdown-minutes">Duration</label><input id="countdown-minutes" type="number" min="1" max="1440" step="1" value={minutes} disabled={timers.state.countdown.endsAt !== null} onChange={event => setMinutes(event.target.value)} onBlur={() => { const value = Number(minutes); if (value >= 1 && value <= 1440) timers.setDuration(value); else setMinutes(String(timers.state.countdown.duration / 60000)); }}/><span>minutes</span></div><div className="timer-controls"><button className="icon-button outlined" onClick={timers.countdownReset} aria-label="Reset countdown"><RotateCcw size={19}/></button><button className="button-primary" onClick={timers.countdownToggle}>{timers.state.countdown.endsAt ? <Pause size={17}/> : <Play size={17}/>} {timers.state.countdown.endsAt ? "Pause" : timers.state.countdown.completed ? "Start again" : "Start"}</button><button className={`icon-button outlined ${timers.sound ? "enabled" : ""}`} onClick={() => void timers.enableSound()} aria-label={timers.sound ? "Disable countdown sound" : "Enable countdown sound"} aria-pressed={timers.sound}>{timers.sound ? <Volume2 size={19}/> : <VolumeX size={19}/>}</button></div><p className="fine-print timer-note">The timer keeps its place when you leave. Sound plays only while this app is open and your browser permits audio.</p></>}
  </div>;
}
