"use client";
import { useState } from "react";
import { ArrowRight, Eye, EyeOff, LoaderCircle, LockKeyhole, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { login } from "@/app/actions";
import { WatchFace } from "@/components/watch-face";
import { PRESETS } from "@/lib/presets";
const flagship = PRESETS.find(preset => preset.id === "reactor")!;
export function PrivateEntrance({ setupRequired = false, unavailable }: { setupRequired?: boolean; unavailable?: string }) {
  const [passphrase, setPassphrase] = useState(""); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await login(passphrase); if (!result.ok) { setError(result.error); setPassphrase(""); } else { setPassphrase(""); router.replace("/"); router.refresh(); } } catch { setError("We couldn’t unlock the studio. Please try again."); } finally { setBusy(false); } }
  return <main className="private-entrance" id="main-content"><div className="entrance-left"><Link className="wordmark entrance-brand" href="/">WATCHMÉ<span className="wordmark-dot">●</span></Link><div className="entrance-content"><span className="eyebrow"><span className="status-dot"/> THE PRIVATE COLLECTION</span><h1>Your time.<br/><span>Your signature.</span></h1><p className="entrance-description">Extraordinary watches.<br/>An entirely personal point of view.</p>
    {setupRequired ? <div className="entrance-notice"><LockKeyhole size={20}/><div><h2>Your studio is almost ready.</h2><p>Private access is being set up. Once it’s ready, your collection will be waiting right here.</p></div></div> : unavailable ? <div className="entrance-notice"><ShieldCheck size={20}/><div><h2>Your collection is taking a moment.</h2><p>{unavailable}</p><button className="text-button" onClick={() => router.refresh()}>Try again <ArrowRight size={15}/></button></div></div> : <form className="entrance-form" onSubmit={submit}><label htmlFor="passphrase">YOUR PRIVATE PASSPHRASE</label><div className="password-field"><LockKeyhole size={17}/><input id="passphrase" name="passphrase" autoComplete="current-password" type={visible ? "text" : "password"} value={passphrase} onChange={event => setPassphrase(event.target.value)} placeholder="Enter your passphrase" minLength={1} maxLength={1024} required autoFocus/><button className="icon-button" type="button" aria-label={visible ? "Hide passphrase" : "Show passphrase"} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div>{error && <p className="inline-error" role="alert">{error}</p>}<button type="submit" className="button-primary" disabled={busy || !passphrase}>{busy ? <LoaderCircle size={17} className="spin"/> : "Enter the studio"}<ArrowRight size={17}/></button><span className="entrance-security"><ShieldCheck size={13}/> Private by design. Yours by choice.</span></form>}
    </div><footer className="entrance-footer">THE ART OF MAKING TIME YOURS.</footer></div><div className="entrance-art"><div className="entrance-art-top"><span className="eyebrow">BLACK LABEL</span><span className="edition-index">07 <span>/ {String(PRESETS.length).padStart(2, "0")}</span></span></div><div className="entrance-watch"><WatchFace design={flagship.design} timezone="America/New_York" live/></div><div className="entrance-art-caption"><div><span className="eyebrow">MECHANICAL CHRONOGRAPH</span><h2>REACTOR.</h2></div><span className="entrance-reference">WM—007<br/>WATCHMÉ BLACK LABEL</span></div></div></main>;
}
