"use client";
import { ArrowUpRight, Download, Eclipse, Flag, Lightbulb, Pause, Play, RotateCcw, Timer } from "lucide-react";
import { formatDuration } from "@/lib/timers";
import type { useTimers } from "@/hooks/use-timers";

export function ReactorConsole({ timers, eclipse, onToggleEclipse, interactiveLight, onToggleLight, onResetLight, onOpenInstruments, onExport }: { timers: ReturnType<typeof useTimers>; eclipse: boolean; onToggleEclipse: () => void; interactiveLight: boolean; onToggleLight: () => void; onResetLight: () => void; onOpenInstruments: () => void; onExport: () => void }) {
  const running = timers.state.chronograph.startedAt !== null;
  return <div className="reactor-console"><div className="reactor-telemetry"><div><span className={`reactor-pulse ${running ? "is-running" : ""}`}/><span>{running ? "CHRONOGRAPH ENGAGED" : "READY WHEN YOU ARE"}</span></div><output aria-label="Chronograph elapsed time">{formatDuration(timers.elapsed, true)}</output><p>Every gear. Every second. Yours.</p></div><div className="reactor-timing-controls"><button className="button-primary" onClick={timers.chronoToggle} aria-label={running ? "Pause chronograph" : "Start chronograph"}>{running ? <Pause size={17}/> : <Play size={17}/>} {running ? "Pause" : timers.elapsed ? "Resume" : "Start"}</button><button className="icon-button outlined" aria-label="Record lap" disabled={!running} onClick={timers.lap}><Flag size={18}/></button><button className="icon-button outlined" aria-label="Reset chronograph" onClick={timers.chronoReset}><RotateCcw size={18}/></button></div><button className="reactor-laps" onClick={onOpenInstruments}><Timer size={15}/><span>{timers.state.chronograph.laps.length ? `${timers.state.chronograph.laps.length} recorded ${timers.state.chronograph.laps.length === 1 ? "lap" : "laps"}` : "Lap history & countdown"}</span><ArrowUpRight size={15}/></button><div className="reactor-environment"><button className={eclipse ? "is-active" : ""} aria-label="Eclipse" aria-pressed={eclipse} onClick={onToggleEclipse}><Eclipse size={20}/><span><strong>Eclipse</strong><small>{eclipse ? "The night has a pulse." : "The dark side of REACTOR."}</small></span><i>{eclipse ? "ON" : "OFF"}</i></button><button className={interactiveLight ? "is-active" : ""} aria-label="Interactive light" aria-pressed={interactiveLight} onClick={onToggleLight}><Lightbulb size={20}/><span><strong>Interactive light</strong><small>Drag to catch a different light.</small></span><i>{interactiveLight ? "ON" : "OFF"}</i></button></div><div className="reactor-light-help"><p>Drag horizontally on your watch. With the watch focused, use the arrow keys to move the light, or Home to reset.</p><button className="text-button" aria-label="Reset light" onClick={onResetLight}><RotateCcw size={13}/> Reset light</button></div><button className="reactor-export" onClick={onExport}><Download size={16}/><span>Download edition card</span><ArrowUpRight size={15}/></button></div>;
}
