"use client";

import { memo, useCallback, useEffect, useRef, useState, type CSSProperties } from "react";
import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronDown, Copy, Expand, Grid2X2, Heart, Info, LoaderCircle, LogOut, Maximize, Moon, MoveUpRight, Pencil, Plus, Redo2, RotateCcw, Settings2, ShieldCheck, SlidersHorizontal, Sun, Timer, Trash2, Undo2, Watch, X } from "lucide-react";
import { deleteWatch, logout, savePreferences, saveWatch, setFavorite } from "@/app/actions";
import { isCompatibleDesign, isComplicationCompatible, normalizeDesign, PARTS, PRESETS } from "@/lib/presets";
import type { Preferences, SavedWatch, StudioData, WatchDesign, WatchPreset } from "@/lib/types";
import { WatchFace } from "@/components/watch-face";
import { Dialog } from "@/components/dialog";
import { Instruments } from "@/components/instruments";
import { StudioSettings, WeatherPanel } from "@/components/studio-settings";
import { useTimers } from "@/hooks/use-timers";
import { useWeather } from "@/hooks/use-weather";
import { useWakeLock } from "@/hooks/use-wake-lock";

const Face = memo(WatchFace);
const METAL_NAMES: Record<string, string> = { steel: "Brushed steel", titanium: "Titanium", gold: "Yellow gold", rose: "Rose gold", graphite: "Graphite" };
const COLORS = [{ name: "Jade", value: "#104D3B" }, { name: "Midnight", value: "#173F65" }, { name: "Obsidian", value: "#141114" }, { name: "Ice", value: "#B8C3CB" }, { name: "Burgundy", value: "#5F2537" }, { name: "Champagne", value: "#B9A584" }, { name: "Ultraviolet", value: "#40346C" }, { name: "Signal", value: "#B74C24" }];
const METAL_COLORS: Record<string, string> = { steel: "linear-gradient(135deg,#f1f0e9,#7e8588 45%,#dedfdb)", titanium: "linear-gradient(135deg,#b3b8b8,#585f66 55%,#d1d4d3)", gold: "linear-gradient(135deg,#f9e2a1,#a7803d 55%,#edce7d)", rose: "linear-gradient(135deg,#f1d0b7,#a56751 55%,#e7b695)", graphite: "linear-gradient(135deg,#6b7072,#232729 55%,#656b6d)" };
type Mode = "collection" | "studio";
type Modal = "settings" | "instruments" | "save" | "rename" | "delete" | "reset" | null;
const draftKey = (id: string) => `watchme.draft.v1.${id}`;
function readDraft(id: string, fallback: WatchDesign): WatchDesign {
  try { const value = localStorage.getItem(draftKey(id)); if (value) { const parsed = JSON.parse(value); if (isCompatibleDesign(parsed)) return parsed; } } catch { /* Invalid drafts cannot override a valid watch. */ }
  return fallback;
}
function titleCase(value: string) { return value.replace(/^./, first => first.toUpperCase()); }

function TimeReadout({ timezone, secondaryTimezone }: { timezone: string; secondaryTimezone: string }) {
  const [now, setNow] = useState<Date | null>(null);
  useEffect(() => { let interval: ReturnType<typeof setInterval> | undefined; const tick = () => setNow(new Date()); const visibility = () => { clearInterval(interval); if (!document.hidden) { tick(); interval = setInterval(tick, 1000); } }; visibility(); document.addEventListener("visibilitychange", visibility); return () => { clearInterval(interval); document.removeEventListener("visibilitychange", visibility); }; }, []);
  const format = (zone: string) => now ? new Intl.DateTimeFormat("en-US", { timeZone: zone || "UTC", hour: "2-digit", minute: "2-digit", hour12: false }).format(now) : "—:—";
  return <div className="time-readout"><div><span className="status-dot"/><span className="time-city">{(timezone.split("/").at(-1) || "Local").replaceAll("_", " ")}</span><strong>{format(timezone)}</strong></div><div><span className="time-city">{(secondaryTimezone.split("/").at(-1) || "London").replaceAll("_", " ")}</span><strong>{format(secondaryTimezone)}</strong></div></div>;
}

const WatchCard = memo(function WatchCard({ item, selected, favorite, timezone, onSelect, onFavorite }: { item: WatchPreset | SavedWatch; selected: boolean; favorite: boolean; timezone: string; onSelect: (id: string) => void; onFavorite: (id: string) => void }) {
  return <article className={`watch-card ${selected ? "selected" : ""}`} style={{ "--card-glow": `${item.design.dialColor}40` } as CSSProperties}>
    <button className="watch-card-main" aria-label={`Select ${item.name}`} aria-pressed={selected} onClick={() => onSelect(item.id)}><div className="card-preview"><Face design={item.design} timezone={timezone} live={false}/></div><div className="card-copy"><span>{item.name}</span><small>{"edition" in item ? item.edition : "YOUR CREATION"}</small></div><span className="card-selected">{selected ? <Check size={12}/> : <ArrowUpRight size={13}/>}</span></button>
    <button className={`card-favorite ${favorite ? "is-favorite" : ""}`} onClick={() => onFavorite(item.id)} aria-label={`${favorite ? "Unfavorite" : "Favorite"} ${item.name}`} aria-pressed={favorite}><Heart size={13} fill={favorite ? "currentColor" : "none"}/></button>
  </article>;
});

function DesignInspector({ design, onChange, onReset, dirty }: { design: WatchDesign; onChange: (design: WatchDesign) => void; onReset: () => void; dirty: boolean }) {
  const update = <K extends keyof WatchDesign>(key: K, value: WatchDesign[K]) => onChange(normalizeDesign({ ...design, [key]: value }));
  return <div className="design-controls">
    <details className="design-section" open><summary><span><small>01</small> Case & finish</span><ChevronDown size={15}/></summary><div className="design-section-body"><label className="select-label">Architecture<select value={design.caseShape} onChange={event => update("caseShape", event.target.value as WatchDesign["caseShape"])}>{PARTS.caseShapes.map(value => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><div className="field-label"><span>Material</span><span>{METAL_NAMES[design.metal]}</span></div><div className="metal-options">{PARTS.metals.map(metal => <button key={metal} aria-label={METAL_NAMES[metal]} title={METAL_NAMES[metal]} aria-pressed={design.metal === metal} className={`metal-swatch ${design.metal === metal ? "selected" : ""}`} style={{ background: METAL_COLORS[metal] }} onClick={() => update("metal", metal)}>{design.metal === metal && <Check size={14}/>}</button>)}</div></div></details>
    <details className="design-section" open><summary><span><small>02</small> Dial</span><ChevronDown size={15}/></summary><div className="design-section-body"><div className="field-label"><span>Color</span><span>{COLORS.find(color => color.value.toLowerCase() === design.dialColor.toLowerCase())?.name || "Custom"}</span></div><div className="color-options">{COLORS.map(color => <button key={color.value} title={color.name} aria-label={`${color.name} dial`} aria-pressed={design.dialColor.toLowerCase() === color.value.toLowerCase()} className={`color-swatch ${design.dialColor.toLowerCase() === color.value.toLowerCase() ? "selected" : ""}`} style={{ background: color.value }} onClick={() => update("dialColor", color.value)}>{design.dialColor.toLowerCase() === color.value.toLowerCase() && <Check size={13}/>}</button>)}<label className="custom-color" title="Custom dial color"><Plus size={15}/><input type="color" aria-label="Custom dial color" value={design.dialColor} onChange={event => update("dialColor", event.target.value)}/></label></div><label className="select-label">Texture<select value={design.texture} onChange={event => update("texture", event.target.value as WatchDesign["texture"])}>{PARTS.textures.map(value => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label></div></details>
    <details className="design-section"><summary><span><small>03</small> Hands & markers</span><ChevronDown size={15}/></summary><div className="design-section-body"><label className="select-label">Hands<select value={design.hands} onChange={event => update("hands", event.target.value as WatchDesign["hands"])}>{PARTS.hands.map(value => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label className="select-label">Hour markers<select value={design.markers} onChange={event => update("markers", event.target.value as WatchDesign["markers"])}>{PARTS.markers.map(value => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label className="accent-input">Accent color<input aria-label="Accent color" type="color" value={design.accentColor} onChange={event => update("accentColor", event.target.value)}/></label></div></details>
    <details className="design-section"><summary><span><small>04</small> Strap & function</span><ChevronDown size={15}/></summary><div className="design-section-body"><label className="select-label">Strap<select value={design.strap} onChange={event => update("strap", event.target.value as WatchDesign["strap"])}>{PARTS.straps.map(value => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label className="select-label">Complication<select value={design.complication} onChange={event => update("complication", event.target.value as WatchDesign["complication"])}>{PARTS.complications.map(value => <option key={value} value={value} disabled={!isComplicationCompatible(design.caseShape, value)}>{value === "gmt" ? "GMT · second time zone" : titleCase(value)}{!isComplicationCompatible(design.caseShape, value) ? " (different case required)" : ""}</option>)}</select></label><p className="fine-print">Every complication has its own fitted layout. Changing the case removes incompatible functions.</p></div></details>
    <button className="text-button reset-design" disabled={!dirty} onClick={onReset}><RotateCcw size={14}/> Reset to original</button>
  </div>;
}

export function WatchStudio({ initialData }: { initialData: StudioData }) {
  const [watches, setWatches] = useState(initialData.watches);
  const [preferences, setPreferencesState] = useState(initialData.preferences);
  const [activeId, setActiveId] = useState(initialData.preferences.activeWatchId);
  const initial = initialData.watches.find(watch => watch.id === initialData.preferences.activeWatchId) || PRESETS.find(preset => preset.id === initialData.preferences.activeWatchId) || PRESETS[0];
  const [history, setHistory] = useState<WatchDesign[]>([initial.design]); const [historyIndex, setHistoryIndex] = useState(0);
  const [mode, setMode] = useState<Mode>("collection"); const [collectionTab, setCollectionTab] = useState<"originals" | "saved">(initialData.watches.some(watch => watch.id === initialData.preferences.activeWatchId) ? "saved" : "originals"); const [favoritesOnly, setFavoritesOnly] = useState(false);
  const [lume, setLume] = useState(false); const [focus, setFocus] = useState(false); const [keepAwake, setKeepAwake] = useState(false); const [mobileInspector, setMobileInspector] = useState(false);
  const [modal, setModal] = useState<Modal>(null); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null); const [ready, setReady] = useState(false);
  const preferenceRef = useRef(preferences); const initialRef = useRef(initial); const preferencesQueue = useRef<Promise<unknown>>(Promise.resolve()); const inspectorRef = useRef<HTMLElement>(null);
  const timers = useTimers(); const weather = useWeather(preferences.location, preferences.unit); const wakeLock = useWakeLock(focus && keepAwake);
  const selected = watches.find(watch => watch.id === activeId) || PRESETS.find(preset => preset.id === activeId) || PRESETS[0];
  const preset = PRESETS.find(item => item.id === selected.design.family) || PRESETS[0]; const design = history[historyIndex];
  const dirty = JSON.stringify(design) !== JSON.stringify(selected.design); const isSaved = !('edition' in selected);
  const notify = useCallback((message: string, error = false) => setToast({ message, error }), []);
  const persistPreferences = useCallback(async (next: Preferences, reportSuccess = false) => {
    preferenceRef.current = next; setPreferencesState(next);
    const operation = preferencesQueue.current.then(async () => { try { const result = await savePreferences(next); if (!result.ok) { notify(result.error, true); return false; } if (reportSuccess) notify("Preferences saved."); return true; } catch { notify("Couldn’t sync preferences. Please try again.", true); return false; } });
    preferencesQueue.current = operation; return operation;
  }, [notify]);
  useEffect(() => {
    const start = initialRef.current; const restored = readDraft(start.id, start.design);
    if (JSON.stringify(restored) !== JSON.stringify(start.design)) { setHistory([start.design, restored]); setHistoryIndex(1); setMode("studio"); notify("Your unfinished design is right where you left it."); }
    if (!preferenceRef.current.primaryTimezone) { const zone = Intl.DateTimeFormat().resolvedOptions().timeZone; void persistPreferences({ ...preferenceRef.current, primaryTimezone: zone }); }
    setReady(true);
  }, [notify, persistPreferences]);
  useEffect(() => { if (!ready) return; try { if (dirty) localStorage.setItem(draftKey(activeId), JSON.stringify(design)); else localStorage.removeItem(draftKey(activeId)); } catch { /* Keep the editor working even without device storage. */ } }, [activeId, design, dirty, ready]);
  useEffect(() => { if (!toast) return; const timeout = setTimeout(() => setToast(null), toast.error ? 10000 : 4500); return () => clearTimeout(timeout); }, [toast]);
  useEffect(() => {
    if (!mobileInspector) return;
    const panel = inspectorRef.current; if (!panel) return;
    const media = window.matchMedia("(max-width: 760px)");
    const opener = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const previousOverflow = document.body.style.overflow;
    const background = [...document.querySelectorAll<HTMLElement>(".workspace-header,.showcase,.collection-section,.workspace-footer,.mobile-customize")];
    const sync = () => {
      background.forEach(element => { element.inert = media.matches; });
      document.body.style.overflow = media.matches ? "hidden" : previousOverflow;
      if (media.matches) { panel.setAttribute("role", "dialog"); panel.setAttribute("aria-modal", "true"); panel.querySelector<HTMLButtonElement>(".mobile-close")?.focus(); }
      else { panel.removeAttribute("role"); panel.removeAttribute("aria-modal"); }
    };
    const trap = (event: KeyboardEvent) => {
      if (!media.matches || event.key !== "Tab" || document.querySelector("dialog[open]")) return;
      const controls = [...panel.querySelectorAll<HTMLElement>("button:not(:disabled),input:not(:disabled),select:not(:disabled),summary,[tabindex='0']")].filter(element => element.getClientRects().length > 0);
      const first = controls[0]; const last = controls.at(-1);
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    sync(); media.addEventListener("change", sync); document.addEventListener("keydown", trap);
    return () => { background.forEach(element => { element.inert = false; }); document.body.style.overflow = previousOverflow; panel.removeAttribute("role"); panel.removeAttribute("aria-modal"); media.removeEventListener("change", sync); document.removeEventListener("keydown", trap); if (media.matches) opener?.focus(); };
  }, [mobileInspector]);
  useEffect(() => { const exit = () => { if (!document.fullscreenElement) setFocus(false); }; document.addEventListener("fullscreenchange", exit); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !document.querySelector("dialog[open]")) { setFocus(false); setMobileInspector(false); } }; document.addEventListener("keydown", key); return () => { document.removeEventListener("fullscreenchange", exit); document.removeEventListener("keydown", key); }; }, []);
  const selectWatch = useCallback((id: string) => {
    const item = watches.find(watch => watch.id === id) || PRESETS.find(watch => watch.id === id); if (!item) return;
    const restored = readDraft(id, item.design); setActiveId(id); setHistory(JSON.stringify(restored) !== JSON.stringify(item.design) ? [item.design, restored] : [item.design]); setHistoryIndex(JSON.stringify(restored) !== JSON.stringify(item.design) ? 1 : 0);
    void persistPreferences({ ...preferenceRef.current, activeWatchId: id });
  }, [watches, persistPreferences]);
  const favoriteWatch = useCallback(async (id: string) => {
    const saved = watches.find(watch => watch.id === id);
    if (saved) { try { const result = await setFavorite(id, !saved.favorite); if (!result.ok) notify(result.error, true); else setWatches(current => current.map(watch => watch.id === id ? result.data : watch)); } catch { notify("Couldn’t update this favorite. Please try again.", true); } }
    else { const list = preferenceRef.current.favoritePresets; await persistPreferences({ ...preferenceRef.current, favoritePresets: list.includes(id) ? list.filter(value => value !== id) : [...list, id] }); }
  }, [watches, notify, persistPreferences]);
  function changeDesign(next: WatchDesign) { setHistory(current => [...current.slice(0, historyIndex + 1), next].slice(-60)); setHistoryIndex(Math.min(historyIndex + 1, 59)); }
  function openNameModal(type: "save" | "rename") { setToast(null); setName(type === "save" && !isSaved ? `${selected.name} No. 01` : selected.name); setModal(type); }
  async function saveCurrent(event: React.FormEvent) {
    event.preventDefault(); setBusy(true);
    try { const result = await saveWatch({ id: isSaved ? selected.id : undefined, name: name.trim(), design: modal === "rename" ? selected.design : design }); if (!result.ok) { notify(result.error, true); return; }
      const watch = result.data; setWatches(current => current.some(item => item.id === watch.id) ? current.map(item => item.id === watch.id ? watch : item) : [watch, ...current]);
      if (modal !== "rename") { try { localStorage.removeItem(draftKey(activeId)); } catch { /* Optional browser storage. */ } setHistory([watch.design]); setHistoryIndex(0); }
      setActiveId(watch.id); setCollectionTab("saved"); setFavoritesOnly(false); setModal(null); await persistPreferences({ ...preferenceRef.current, activeWatchId: watch.id }); notify(modal === "rename" ? "A new name. The same excellent taste." : "Your creation is in the collection.");
    } catch { notify("Couldn’t save your watch. Your draft is still here.", true); } finally { setBusy(false); }
  }
  async function duplicate() { if (busy) return; setBusy(true); try { const result = await saveWatch({ name: `${selected.name} II`, design }); if (!result.ok) { notify(result.error, true); return; } setWatches(current => [result.data, ...current]); setActiveId(result.data.id); setHistory([result.data.design]); setHistoryIndex(0); setCollectionTab("saved"); setFavoritesOnly(false); await persistPreferences({ ...preferenceRef.current, activeWatchId: result.data.id }); notify("A fresh canvas. Make this one yours."); } catch { notify("Couldn’t duplicate this watch. Please try again.", true); } finally { setBusy(false); } }
  async function removeCurrent() { if (!isSaved) return; setBusy(true); try { const result = await deleteWatch(selected.id); if (!result.ok) { notify(result.error, true); return; } setWatches(current => current.filter(watch => watch.id !== selected.id)); try { localStorage.removeItem(draftKey(selected.id)); } catch {} setActiveId(PRESETS[0].id); setHistory([PRESETS[0].design]); setHistoryIndex(0); setModal(null); await persistPreferences({ ...preferenceRef.current, activeWatchId: PRESETS[0].id }); notify("Watch removed from your collection."); } catch { notify("Couldn’t remove this watch. Please try again.", true); } finally { setBusy(false); } }
  async function enterFocus() { setFocus(true); setMobileInspector(false); try { if (document.documentElement.requestFullscreen) await document.documentElement.requestFullscreen(); } catch { /* The in-page focus layout provides the same uncluttered view. */ } }
  async function exitFocus() { setFocus(false); if (document.fullscreenElement) { try { await document.exitFullscreen(); } catch { /* In-page focus is already closed. */ } } }
  const isFavorite = (id: string) => watches.find(watch => watch.id === id)?.favorite || preferences.favoritePresets.includes(id);
  const collection = (collectionTab === "originals" ? PRESETS : watches).filter(item => !favoritesOnly || isFavorite(item.id));
  const activeIndex = PRESETS.findIndex(item => item.id === design.family) + 1;
  return <div className={`studio-shell ${focus ? "is-focus" : ""} ${lume ? "is-lume" : ""}`}>
    <aside className="navigation-rail"><Link className="brand-symbol" href="/" aria-label="Watchme home"><span/><span/><span/></Link><nav aria-label="Workspace"><button className={`rail-button ${mode === "collection" ? "active" : ""}`} aria-label="Collection" title="Collection" onClick={() => { setMode("collection"); setMobileInspector(false); }}><Grid2X2 size={20}/></button><button className={`rail-button ${mode === "studio" ? "active" : ""}`} aria-label="Design studio" title="Design studio" onClick={() => { setMode("studio"); setMobileInspector(true); }}><SlidersHorizontal size={20}/></button><button className="rail-button" aria-label="Chronograph and countdown" title="Instruments" onClick={() => setModal("instruments")}><Timer size={21}/></button><button className="rail-button" aria-label="Enter focus mode" title="Focus mode" onClick={() => void enterFocus()}><Maximize size={19}/></button></nav><div className="rail-bottom"><button className="rail-button" aria-label="Settings" title="Settings" onClick={() => setModal("settings")}><Settings2 size={19}/></button><button className="profile-button" title="Lock the studio" aria-label="Lock the studio" onClick={() => void logout()}><LogOut size={16}/></button></div></aside>
    <div className="workspace"><header className="workspace-header"><Link className="wordmark" href="/">WATCHME<span className="wordmark-dot">●</span></Link><div className="header-divider"/><span className="workspace-title">Your private watch studio</span><nav className="header-nav" aria-label="Views"><button className={mode === "collection" ? "active" : ""} onClick={() => { setMode("collection"); setMobileInspector(false); }}>Collection</button><button className={mode === "studio" ? "active" : ""} onClick={() => { setMode("studio"); setMobileInspector(true); }}>Design studio<span className="tiny-plus">+</span></button></nav><button className="icon-button mobile-settings" aria-label="Settings" onClick={() => setModal("settings")}><Settings2 size={17}/></button><span className="private-badge"><span className="status-dot"/> PRIVATE COLLECTION</span></header>
      <main id="main-content"><div className="main-stage"><section className="showcase" aria-label={`${selected.name} live watch`} style={{ "--watch-glow": `${design.dialColor}28` } as CSSProperties}>
        <div className="hero-topline"><span className="eyebrow">{mode === "studio" ? "THE DESIGN STUDIO" : "TIME. ON YOUR TERMS."}</span><span className="edition-index">{String(activeIndex).padStart(2, "0")}<span> / 06</span></span></div>
        <div className="watch-story"><div className="edition-pill"><span/>{isSaved ? "A WATCHME ORIGINAL BY YOU" : preset.category}</div><h1 className={selected.name.length > 18 ? "long-name" : undefined} title={selected.name}>{selected.name}</h1><p>{isSaved ? "Considered in every detail. Entirely yours." : preset.description}</p><span className="watch-reference">WM—{String(activeIndex).padStart(3, "0")} <span>/</span> {isSaved ? "CUSTOM EDITION" : preset.edition.split(" / ")[0]}</span></div>
        <div className="hero-art"><div className="hero-orbit"/><div className="watch-stage"><Face design={design} timezone={preferences.primaryTimezone || "UTC"} secondaryTimezone={preferences.secondaryTimezone} lume={lume} live={true} chronographElapsed={design.complication === "chronograph" ? timers.elapsed : 0} weather={weather.weather ?? undefined}/></div><span className="watch-caption"><span/> DESIGNED TO BE DIFFERENT</span></div>
        <div className="hero-bottomline"><div className="hero-material"><span className="eyebrow">{METAL_NAMES[design.metal].toUpperCase()}</span><span>{titleCase(design.texture)} dial <i/> {design.strap === "bracelet" ? "Integrated bracelet" : `${titleCase(design.strap)} strap`}</span></div><div className="view-controls"><button className="icon-button mobile-details" aria-label="Watch details" onClick={() => { setMode("collection"); setMobileInspector(true); }}><Info size={17}/></button><button aria-label={lume ? "Disable lume" : "Enable lume"} title="Luminous dial" aria-pressed={lume} className={`icon-button ${lume ? "enabled" : ""}`} onClick={() => setLume(!lume)}>{lume ? <Sun size={17}/> : <Moon size={17}/>}</button><span/><button className="icon-button" aria-label="Enter focus mode" title="Focus mode" onClick={() => void enterFocus()}><Expand size={17}/></button></div></div>
        {mode === "studio" && <div className="history-controls"><button className="icon-button" disabled={historyIndex === 0} onClick={() => setHistoryIndex(index => index - 1)} aria-label="Undo change"><Undo2 size={16}/></button><button className="icon-button" disabled={historyIndex === history.length - 1} onClick={() => setHistoryIndex(index => index + 1)} aria-label="Redo change"><Redo2 size={16}/></button><span>{dirty ? "Draft saved on this device" : "All in good time"}</span></div>}
      </section>
      <aside ref={inspectorRef} className={`inspector ${mobileInspector ? "mobile-open" : ""}`} aria-label={mode === "studio" ? "Watch customization" : "Watch details"}>
        <div className="inspector-heading"><div><span className="eyebrow">{mode === "studio" ? "MAKE IT YOURS" : "THE FINER DETAILS"}</span><h2>{mode === "studio" ? "The essentials." : "A closer look."}</h2></div><button className="icon-button mobile-close" aria-label="Close customization" onClick={() => setMobileInspector(false)}><X size={20}/></button>{mode === "collection" && <span className="inspector-asterisk">✳</span>}</div>
        {mode === "studio" ? <><DesignInspector design={design} onChange={changeDesign} onReset={() => setModal("reset")} dirty={dirty}/><div className="inspector-save"><button className="button-primary" onClick={() => openNameModal("save")} disabled={busy}><Plus size={16}/>{isSaved ? "Save changes" : "Add to collection"}</button><p>Your design. Your signature.</p></div></> : <><div className="watch-specs"><div><span>Case</span><strong>{titleCase(design.caseShape)}</strong></div><div><span>Material</span><strong>{METAL_NAMES[design.metal]}</strong></div><div><span>Dial</span><strong>{titleCase(design.texture)}</strong></div><div><span>Function</span><strong>{design.complication === "none" ? "Time only" : design.complication === "gmt" ? "Dual time · GMT" : titleCase(design.complication)}</strong></div></div><button className="customize-button" onClick={() => { setMode("studio"); setMobileInspector(true); }}><span><SlidersHorizontal size={16}/> Make it yours</span><ArrowUpRight size={18}/></button><div className="ownership-actions"><button className={`text-button ${isFavorite(selected.id) ? "is-favorite" : ""}`} onClick={() => void favoriteWatch(selected.id)} aria-pressed={isFavorite(selected.id)}><Heart size={14} fill={isFavorite(selected.id) ? "currentColor" : "none"}/>{isFavorite(selected.id) ? "Favorited" : "Favorite"}</button><button className="text-button" onClick={() => void duplicate()} disabled={busy}><Copy size={14}/>Duplicate</button>{isSaved && <><button className="text-button" onClick={() => openNameModal("rename")}><Pencil size={14}/>Rename</button><button className="text-button" onClick={() => setModal("delete")}><Trash2 size={14}/>Remove</button></>}</div><WeatherPanel location={preferences.location} weather={weather.weather} loading={weather.loading} error={weather.error} stale={weather.stale} unit={preferences.unit} onSettings={() => setModal("settings")} onRefresh={() => void weather.refresh()}/></>}
        <div className="inspector-footer"><ShieldCheck size={13}/><span>YOURS. AND YOURS ALONE.</span></div>
      </aside></div>
      <section className="collection-section" aria-label="Watch collection"><div className="collection-heading"><div className="collection-title"><span className="eyebrow">THE COLLECTION</span><span className="collection-count">{String(collection.length).padStart(2, "0")}</span></div><div className="collection-tabs" role="group" aria-label="Collection filter"><button className={collectionTab === "originals" ? "selected" : ""} onClick={() => setCollectionTab("originals")}>Originals</button><button className={collectionTab === "saved" ? "selected" : ""} onClick={() => setCollectionTab("saved")}>My creations <span>{watches.length}</span></button><button className={`favorites-filter ${favoritesOnly ? "selected" : ""}`} aria-label="Show favorites only" aria-pressed={favoritesOnly} onClick={() => setFavoritesOnly(!favoritesOnly)}><Heart size={14} fill={favoritesOnly ? "currentColor" : "none"}/></button></div><span className="collection-hint">GOOD TASTE IS PERSONAL<ArrowDown size={13}/></span></div>
        <div className="watch-collection">{collection.map(item => <WatchCard key={item.id} item={item} selected={item.id === activeId} favorite={Boolean(isFavorite(item.id))} timezone={preferences.primaryTimezone || "UTC"} onSelect={selectWatch} onFavorite={favoriteWatch}/>)}{!collection.length && <div className="collection-empty"><Watch size={24} strokeWidth={1}/><div><strong>{favoritesOnly ? "Your favorites go here." : "Your next original starts here."}</strong><p>{favoritesOnly ? "Tap the heart on a watch to keep it close." : "Start with any design. Make every detail your own."}</p></div><button className="text-button" onClick={() => { setFavoritesOnly(false); setCollectionTab("originals"); setMode("studio"); setMobileInspector(true); }}>Explore the studio<ArrowRight size={16}/></button></div>}</div>
      </section></main>
      <footer className="workspace-footer"><span>WATCHME <i/> THE ART OF MAKING TIME YOURS.</span><TimeReadout timezone={preferences.primaryTimezone || "UTC"} secondaryTimezone={preferences.secondaryTimezone}/><button onClick={() => setModal("instruments")}><Timer size={13}/> Instruments<MoveUpRight size={12}/></button></footer>
    </div>
    <button className="mobile-customize" onClick={() => { setMode("studio"); setMobileInspector(true); }}><SlidersHorizontal size={17}/> Customize {dirty && <span className="status-dot"/>}</button>
    {focus && <div className="focus-controls"><button className="text-button" onClick={() => void exitFocus()}><ArrowLeft size={17}/> Back to the studio</button><div><button className={`text-button ${lume ? "enabled" : ""}`} onClick={() => setLume(!lume)} aria-pressed={lume}><Moon size={16}/> Lume</button><button className={`text-button ${wakeLock.active ? "enabled" : ""}`} onClick={() => setKeepAwake(!keepAwake)} aria-pressed={keepAwake}><Sun size={16}/>{wakeLock.active ? "Staying awake" : "Keep awake"}</button></div>{wakeLock.error && <p role="status">{wakeLock.error}</p>}</div>}
    {timers.state.countdown.completed && modal !== "instruments" && <div className="countdown-banner" role="status"><Timer size={17}/><span>Time’s up.</span><button onClick={() => setModal("instruments")}>Open timer<ArrowUpRight size={14}/></button><button className="icon-button" aria-label="Dismiss countdown completion" onClick={timers.countdownReset}><X size={14}/></button></div>}
    {toast && !modal && <div className={`toast ${toast.error ? "toast-error" : ""}`} role={toast.error ? "alert" : "status"}>{toast.error ? <X size={16}/> : <Check size={16}/>}<span>{toast.message}</span><button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast(null)}><X size={14}/></button></div>}
    {modal === "settings" && <Dialog notice={toast?.error ? toast : null} title="Set your own pace." eyebrow="PREFERENCES" onClose={() => setModal(null)} wide><StudioSettings preferences={preferences} busy={busy} onLock={() => void logout()} onSave={async next => { setBusy(true); const success = await persistPreferences(next, true); setBusy(false); if (success) setModal(null); }}/></Dialog>}
    {modal === "instruments" && <Dialog notice={toast?.error ? toast : null} title="Every second counts." eyebrow="THE INSTRUMENTS" onClose={() => setModal(null)}><Instruments timers={timers}/></Dialog>}
    {(modal === "save" || modal === "rename") && <Dialog notice={toast?.error ? toast : null} title={modal === "rename" ? "Give it a name." : "Sign your creation."} eyebrow="YOUR COLLECTION" onClose={() => { if (!busy) setModal(null); }}><form onSubmit={saveCurrent} className="name-form"><p className="muted">{modal === "rename" ? "A name worthy of your watch." : "One of a kind. Made by you. Saved to your private collection."}</p><label>Watch name<input autoFocus value={name} onChange={event => setName(event.target.value)} required maxLength={60} minLength={1} placeholder="Your watch’s name"/></label><div className="dialog-actions"><button type="button" className="button-secondary" onClick={() => setModal(null)} disabled={busy}>Cancel</button><button type="submit" className="button-primary" disabled={busy || !name.trim()}>{busy ? <LoaderCircle size={16} className="spin"/> : <Check size={16}/>} {modal === "rename" ? "Rename watch" : "Save watch"}</button></div></form></Dialog>}
    {modal === "delete" && <Dialog notice={toast?.error ? toast : null} title="Let this one go?" eyebrow="REMOVE WATCH" onClose={() => { if (!busy) setModal(null); }}><p className="muted">“{selected.name}” will be removed from your saved collection. The original design will always be here to start again.</p><div className="dialog-actions"><button className="button-secondary" onClick={() => setModal(null)} disabled={busy}>Keep it</button><button className="button-danger" onClick={() => void removeCurrent()} disabled={busy}>{busy ? <LoaderCircle size={16} className="spin"/> : <Trash2 size={16}/>} Remove watch</button></div></Dialog>}
    {modal === "reset" && <Dialog notice={toast?.error ? toast : null} title="Back to the beginning." eyebrow="RESET DESIGN" onClose={() => setModal(null)}><p className="muted">Restore the selected watch’s saved design. You can still undo this change in the studio.</p><div className="dialog-actions"><button className="button-secondary" onClick={() => setModal(null)}>Keep designing</button><button className="button-primary" onClick={() => { changeDesign(selected.design); setModal(null); }}>Reset design</button></div></Dialog>}
  </div>;
}
